[workspace]
members = ["crates/context-logger", "crates/context-logger-derive"]
resolver = "3"

[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/alekseysidorov/context-logger"
license = "MIT OR Apache-2.0"

[workspace.metadata.crane]
name = "context-logger"

[workspace.dependencies]
context-logger-derive = { path = "crates/context-logger-derive", version = "0.2.1" }
env_logger = { version = "0.11", features = ["kv"] }
log = { version = "0.4.33", features = ["kv_serde"] }
manyhow = "0.14"
pretty_assertions = "1.4"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
serde_json = "1.0"
strum = { version = "0.28", features = ["derive"] }
syn = { version = "3", features = ["full", "extra-traits"] }
trybuild = "1"
tokio = { version = "1.53", features = ["macros", "rt-multi-thread", "time"] }

[workspace.lints.clippy]
missing_errors_doc = "warn"
missing_panics_doc = "warn"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace.lints.rust]
missing_debug_implementations = "warn"
unsafe_code = "forbid"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
