[workspace]
members = ["context-logger-macro"]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/alekseysidorov/context-logger"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
manyhow = "0.14"
pretty_assertions = "1.4"
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full", "extra-traits"] }
strum = { version = "0.27", features = ["derive"] }
tokio = { version = "1.53", features = ["macros", "rt-multi-thread", "time"] }

[workspace.lints.clippy]
missing_errors_doc = "warn"
missing_panics_doc = "warn"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace.lints.rust]
missing_debug_implementations = "warn"
unsafe_code = "forbid"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[package]
name = "context-logger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

description = "A small structured context propagation layer for the standard Rust log ecosystem."
documentation = "https://docs.rs/crate/context-logger"
repository.workspace = true
license.workspace = true

keywords = [
  "context-logging",
  "log",
  "logging",
  "structured-logging",
  "tracing",
]
categories = ["asynchronous", "development-tools::debugging"]

[features]
default = ["derive"]
derive = ["dep:context-logger-macro"]

[dependencies]
context-logger-macro = { path = "context-logger-macro", optional = true }

erased-serde = "0.4.10"
include-utils = "0.2.4"
log = { version = "0.4.33", features = ["kv_serde"] }
pin-project = "1"
serde = "1"

[dev-dependencies]
chrono = "0.4"
env_logger = { version = "0.11", features = ["kv"] }
futures-util = "0.3"
pretty_assertions = "1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1"
structured-logger = { version = "1.0" }
tokio.workspace = true

[lints]
workspace = true
